Lite Minifier Option
malware-dev/MDK-SE pull request #213
Opened 2020-11-14 19:54 UTC by SCBionicle

This does all the steps of minifying except for renaming symbols so that it's easier to debug stacktraces thrown out in the wilderness of the Steam Workshop while still having your code minified.

Note: commit 43198d707633fcc5821601105bfa73a6c995ba4a was to enable the compiler to build and this can be reverted as it broke some other functionality.

Fixes #212

2020-11-14 19:58 UTC, SCBionicle commented on Source/MDKUtilities/MDKUtilities.csproj
> +    <Reference Include="netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" />
@malware-dev this isn't needed and can be reverted. I needed to add this in just so it'll compile.

2020-11-14 19:58 UTC, SCBionicle commented on Source/MDKWhitelistExtractor/MDKWhitelistExtractor.csproj
> +    <Reference Include="netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" />
@malware-dev same as in https://github.com/malware-dev/MDK-SE/pull/213/files#r523456985

2020-11-15 08:12 UTC, SCBionicle commented
@malware-dev this should be ready now. I thought I had everything done before but turns out I set up the project incorrectly. Could you review this now?

2020-11-15 15:58 UTC, malware-dev requested changes
Looks generally fine, except for the pragma.

2020-11-15 15:58 UTC, malware-dev commented on Source/MDK/Build/Composers/Minifying/MinifyingComposer.cs
> +#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
Remove these pragmas please.

2020-11-15 18:27 UTC, SCBionicle commented on Source/MDK/Build/Composers/Minifying/MinifyingComposer.cs
> +#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
I removed them, can you take a look?

2020-11-16 07:24 UTC, malware-dev approved these changes

2020-11-16 07:24 UTC, merged